### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by bahim22** [bahim22/work#12]
# Finish most recent modules 
- qrcode module
- [x] Refactor to optimize
- [x] Get user input for data and color more succinctly
- calendar module
- [ ] Add ICALENDAR module to replace py cal

- Add Docstrings and tests for previous modules
- extract completed modules and deploy to seperate repo to be used in Python practice and guide website

**Comment by bahim22** [comment]
# Edits to refactor main sections

- [ ] mv aplus section to separate repo in order to convert to doc site
- [x] Use pyproject.toml format for requirements and then pip-tools or pip-wheels
- [ ] Remove unnecessary deps and convert ipynb to refactored py
- [x] Reorganize OS, scripting, and data files
- [x] **init JS, SysAd sections**

**Comment by bahim22** [comment]
1. Adjusted dir for Docs site refactor
2. Installed deps with wheels
3. Repo will focus on python practice
4. Will doc system info in separate repo
