### ISSUE TITLE
220-1102 & 1101 Note sections

### ISSUE THREAD

**Issue by bahim22** [bahim22/work#13]
# A+ documentation info

### Review

- [x] Read
- [x] Practice questions

- [x] **Hardware**
- [x] **Network** 
- [x] **Scripting & remote access**
- [x] **Mobile Devices**
- [x] **Virtualization **

------

## ToDo

- [x] Finish Notes
- [x] Review and Read
- [x] Practice questions

- [x] **Operating System**
  > Windows
  > macOS
  > Linux
  > Mobile
- [x] **Security**
- [x] **Operational procedures**
- [x] **Troubleshooting**
  > Software
  > Hardware
  > Network

### 5 Days

- Notes and main practice exam sessions relate to network, hardware and reviewing information I already knew.
- Utilized multiple apps and programs such as Microsoft To-do, Planner, OneNote; Adobe Acrobat; Visual Studio Code, Windows 10, 11, WSL
- Need to focus on reading the course material, practice exams, and subsections that don't have completed notes

**Comment by bahim22** [comment]
Printers 
- Sequence of events
- Troubleshooting
- Difference between

- Windows lab scenario 


- Laser printer process
Processing
Charging
Exposing
Developing
Transferring
Fusing
Cleaning

**Comment by bahim22** [comment]
# read and review S/Su

- [x] Windows features and tools
- [x] Network
- IP config, Ports, setup, tools
- [x] Hardware
- PSU, I/O & peripherals, printers
- [ ] Op Process
- Scripts, assets & change management
